name: Deploy to Heroku

on:
  push:
    branches:
      - main
      - OzPol* # Deploy any branch starting with 'OzPol'
      - dev*
  workflow_dispatch:

jobs:
  deploy-to-heroku:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 # Unshallow the repository

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'

      - name: Set up environment variables
        run: |
          echo "DATABASE_URL=${{ secrets.DATABASE_URL }}" >> $GITHUB_ENV
          echo "EMAIL_USERNAME=${{ secrets.EMAIL_USERNAME }}" >> $GITHUB_ENV
          echo "EMAIL_PASSWORD=${{ secrets.EMAIL_PASSWORD }}" >> $GITHUB_ENV

      - name: Install dependencies
        run: npm install

      - name: Build the project
        run: npm run build

      - name: Install Heroku CLI
        run: curl https://cli-assets.heroku.com/install.sh | sh

      - name: Authenticate with Heroku
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        run: echo $HEROKU_API_KEY | heroku auth:token

      - name: Set up Git user
        run: |
          git config --global user.email "probookerdb@gmail.com"
          git config --global user.name "OzPol"

      - name: Pull latest changes and rebase
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        run: |
          heroku git:remote -a probooker-app
          git pull https://heroku:${{ secrets.HEROKU_API_KEY }}@git.heroku.com/probooker-app.git main --rebase || git rebase --abort

      - name: Deploy to Heroku
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        run: |
          git push https://heroku:${{ secrets.HEROKU_API_KEY }}@git.heroku.com/probooker-app.git HEAD:main --force
